### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by johnnychq** [johnnychq/todo#1]
- [x] docker
- [ ] Gatsby.js
- [ ] next.js
- [ ] gzip压缩算法与前端文件压缩
- [ ] egg/nginx限制上传大小的问题
- [ ] 区块链技术
- [ ] 深度学习or应用
- [ ] grapesjs
- [ ] 分享
  - [x] 分享cathay-fetch
  - [ ] 分享单点登陆
  - [ ] 分享oss
  - [ ] 国泰单点登陆梳理与分享
  - [ ] 分享npm
    * 模块的概念
    * npm2 vs npm3
    * npm cnpm yarn pnpm
- [ ] gateway技术栈
- [x] 微信支付
- [x] 监控不生效问题
- [x] https不生效问题
- [x] 蚂蚁登陆身份信息授权
- [x] 技术栈去root化
- [x] 官网安全问题
- [x] 钉钉审批中心DMS化
- [x] git的swagger优化
- [x] 金融云小程序管理
- [x] 业务架构梳理
   - [x] utils
- [ ] 技术学习
   - [ ] 通用知识学习
      - [ ] HR系统知识学习
      - [ ] 保险知识学习
   - [ ] 函数式编程
   - [ ] dva
   - [ ] app学习
     - [x] ios
     - [x] android
     - [ ] weex
     - [ ] react-native
     - [ ] dcloud
   - [ ] java学习
     - [x] maven
     - [ ] springboot
     - [ ] sofalite
     - [ ] android
- [ ] 系统平台
  - [ ] demo平台
  - [x] CMS
  - [x] img托管(static server)
- [x] 代码规范
  - [x] 代码规范文档
  - [x] eslint
- [ ] swagger自动mock方案
- [ ] SOFA	
    - [x] SOFA-RPC
        - [x] SOFA-RPC-CLIENT 直连
        - [ ] SOFA-RPC-CLIENT SHARE CONFIG SERVER
        - [x] SOFA-RPC-CLIENT DEPENDENT SERVER
        - [x] SOFA-RPC-SERVER 直连
        - [ ] SOFA-RPC-SERVER SHARE CONFIG SERVER
        - [ ] SOFA-RPC-SERVER DEPENDENT SERVER
    - [x] SOFA-DMS
- [ ] 国泰OA集成
  - [ ] 云邮箱集成
  - [ ] BPM集成钉钉
  - [x] BBS暴露外网
  - [x] sso暴露外网
- [x] 移动开发规范
  - [x] UE稿规范
  - [x] 前端"尺寸"规范
     - [x] viewport规范
     - [x] rem
     - [x] dpr

----------

### 生产问题

- [x] 员工中心->钉钉出错不报警
- [x] 员工中心->钉钉周末未收到报告

**Comment by johnnychq** [comment]
- [x] devops bugfix
